import Head from 'next/head';
import formImage from '../public/form.png';
import Image from 'next/image';
import { useFormik } from 'formik';
import * as Yup from 'yup';
import { useRouter } from 'next/router';
import { motion as m } from 'framer-motion';
import { useRef } from 'react';

export default function Home() {
  const router = useRouter();

  const ref = useRef(null);

  const handleClick = () => {
    // 👇️ reset input field's value
    ref.current.value = '';
  };

  const formik = useFormik({
    initialValues: {
      name: '',
    },

    validationSchema: Yup.object({
      name: Yup.string()
        .min(3, 'Too Short!')
        .max(10, 'Name must be 10 characters or less.')
        .required('Name is required')
        .matches(/^[a-zA-Z]+(([',. -][a-zA-Z ])?[a-zA-Z]*)*$/g, 'Invalid name')
        .matches(/^(?!.*(\w)\1{2,}).+$/g, 'Invalid name'),
    }),

    onSubmit: (values) => {
      console.log('form submitted');
      console.log(values);
      router.push({ pathname: '/success', query: values });
    },
  });

  return (
    <m.div
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      exit={{ opacity: 0 }}
      className="absolute w-full"
    >
      <Head>
        <title>Only Us</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="  h-screen items-center flex justify-center">
        <form
          onSubmit={formik.handleSubmit}
          className="bg-white flex drop-shadow-xl rounded-lg w-4/5 font-latoRegular"
        >
          <div className="flex-1 text-gray-700  p-10">
            <div className="flex items-center border-b border-violet-800 py-2">
              <input
                className="appearance-none border-none bg-transparent  w-full text-gray-700 mr-1 py-1 px-2 leading-tight focus:outline-none"
                ref={ref}
                aria-label="Full name"
                placeholder="Enter your name"
                onChange={formik.handleChange}
                value={formik.values.name}
                onBlur={formik.handleBlur}
                name="name"
              />

              <button
                className="flex-shrink-0 border-transparent text-violet-800 hover:text-violet-950 font-bold rounded"
                type="button"
                onClick={handleClick}
              >
                X
              </button>
            </div>
            <div className="mt-5 ">
              <label
                htmlFor="name"
                className={`block font-latoBold text-sm pb-2 ${
                  formik.touched.name && formik.errors.name
                    ? 'text-red-400'
                    : ''
                } `}
              >
                {formik.touched.name && formik.errors.name
                  ? formik.errors.name
                  : ''}
              </label>
              <p className="text-sm font-latoBold text-red-400 "></p>
            </div>

            <div className="mt-6 ">
              <button
                type="submit"
                className="bg-violet-800 hover:bg-violet-900 font-latoBold text-sm text-white py-3 mt-6 rounded-lg w-full"
              >
                Check your stuff!
              </button>
            </div>
          </div>
        </form>
      </main>
    </m.div>
  );
}
